# Is it the workflow's name or the job's name that should be referred to in
# required status checks?
name: Workflow
on:
  pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  gradle:
    name: Job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
