name: test
on:
  pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      checks: write
      contents: read
      deployments: write
    steps:
    - name: Colors
      run: |
        printf '> formatting:\n'
        printf '\033[1m bold \033[0m\n'
        printf '\033[2m faint \033[0m\n'
        printf '\033[3m italic \033[0m\n'
        printf '\033[4m underline \033[0m\n'
        printf '\033[5m blinking \033[0m\n'
        printf '\033[7m reverse \033[0m\n'
        printf '\033[8m hidden \033[0m\n'
        printf '\033[9m strikethrough \033[0m\n'
        printf '\n'
        printf '> foreground:\n'
        printf '\033[30m black \033[0m\n'
        printf '\033[31m red \033[0m\n'
        printf '\033[32m green \033[0m\n'
        printf '\033[33m yellow \033[0m\n'
        printf '\033[34m blue \033[0m\n'
        printf '\033[35m magenta \033[0m\n'
        printf '\033[36m cyan \033[0m\n'
        printf '\033[37m white \033[0m\n'
        printf '\n'
        printf '> bright foreground:\n'
        printf '\033[1;30m black \033[0m\n'
        printf '\033[1;31m red \033[0m\n'
        printf '\033[1;32m green \033[0m\n'
        printf '\033[1;33m yellow \033[0m\n'
        printf '\033[1;34m blue \033[0m\n'
        printf '\033[1;35m magenta \033[0m\n'
        printf '\033[1;36m cyan \033[0m\n'
        printf '\033[1;37m white \033[0m\n'
        printf '\n'
        printf '> faint foreground:\n'
        printf '\033[2;30m black \033[0m\n'
        printf '\033[2;31m red \033[0m\n'
        printf '\033[2;32m green \033[0m\n'
        printf '\033[2;33m yellow \033[0m\n'
        printf '\033[2;34m blue \033[0m\n'
        printf '\033[2;35m magenta \033[0m\n'
        printf '\033[2;36m cyan \033[0m\n'
        printf '\033[2;37m white \033[0m\n'
        printf '\n'
        printf '> bright foreground (aixterm):\n'
        printf '\033[90m black \033[0m\n'
        printf '\033[91m red \033[0m\n'
        printf '\033[92m green \033[0m\n'
        printf '\033[93m yellow \033[0m\n'
        printf '\033[94m blue \033[0m\n'
        printf '\033[95m magenta \033[0m\n'
        printf '\033[96m cyan \033[0m\n'
        printf '\033[97m white \033[0m\n'
        printf '\n'
        printf '> background:\n'
        printf '\033[40m black \033[0m\n'
        printf '\033[41m red \033[0m\n'
        printf '\033[42m green \033[0m\n'
        printf '\033[43m yellow \033[0m\n'
        printf '\033[44m blue \033[0m\n'
        printf '\033[45m magenta \033[0m\n'
        printf '\033[46m cyan \033[0m\n'
        printf '\033[47m white \033[0m\n'
        printf '\n'
        printf '> faint background:\n'
        printf '\033[100m black \033[0m\n'
        printf '\033[101m red \033[0m\n'
        printf '\033[102m green \033[0m\n'
        printf '\033[103m yellow \033[0m\n'
        printf '\033[104m blue \033[0m\n'
        printf '\033[105m magenta \033[0m\n'
        printf '\033[106m cyan \033[0m\n'
        printf '\033[107m white \033[0m\n'
        printf '\n'
        printf '> box:\n'
        printf '\033[37;40m black \033[0m\n'
        printf '\033[30;44m blue \033[0m\n'
        printf '\033[30;46m cyan \033[0m\n'
        printf '\033[30;42m green  \033[0m\n'
        printf '\033[30;45m magenta  \033[0m\n'
        printf '\033[30;41m red  \033[0m\n'
        printf '\033[30;47m white \033[0m\n'
        printf '\033[30;43m yellow \033[0m\n'
        printf '\n'
        printf '> hyperlink:\n'
        printf '\e]8;;https://github.com/\e\\GitHub\e]8;;\e\\'
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: ./.github/workflows/test
      env:
        GITHUB_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
