name: test
on:
  pull_request:
    branches:
    - main
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      checks: write
      contents: read
      deployments: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: ./.github/workflows/test
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
