name: test
on:
  pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      checks: write
      contents: read
      deployments: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: ./.github/workflows/test
      env:
        GITHUB_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
