name: test
on:
  pull_request:
    branches:
    - main
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      deployments: write
    steps:
    - uses: actions/checkout@v2
    - run: exec python3 -u .github/workflows/test.py
